local options = {
  ensure_installed = {
    "csharp-language-server",
    "clangd",
    "clang-format",
    "cpptools",
    "gopls",
    "gospel",
    "codelldb",
    "lua-language-server",
    "pylint",
    "pyright",
    "erlang-ls",
    "typescript-language-server",
    "vim-language-server",
    "tailwindcss-language-server",
    "yaml-language-server",
    "yamlfix",
    "stylua",
    "ansible-language-server",
    "bash-language-server",
    "cmake-language-server",
    "docker-compose-language-service",
    "dockerfile-language-server",
    "elixir-ls",
    "erlang-ls",
    "gradle-language-server",
    "json-lsp",
    "kotlin-language-server",
    "ktlint",
    "phpactor",
    "phpstan",
    "phpcs",
    "php-cs-fixer",
    "phpcbf",
    "phpmd",
    "prettier",
    "ruby-lsp",
    "debugpy",
    "delve",
    "js-debug-adapter",
    "netcoredbg",
    "java-debug-adapter",
    "kotlin-debug-adapter",
    "php-debug-adapter",
    "zls",
    "fortls",
  },
  PATH = "skip",

  ui = {
    icons = {
      package_pending = " ",
      package_installed = "󰄳 ",
      package_uninstalled = " 󰚌",
    },

    keymaps = {
      toggle_server_expand = "<CR>",
      install_server = "i",
      update_server = "u",
      check_server_version = "c",
      update_all_servers = "U",
      check_outdated_servers = "C",
      uninstall_server = "X",
      cancel_installation = "<C-c>",
    },
  },

  max_concurrent_installers = 10,
}

return options
